import type { Product } from "../types";

const USD = "USD";

/**
 * Representative seed catalog drawn from the real Depris Beauty inventory
 * (categories, brand "Bellmona", copper-peptide signature, $13–$95 range).
 * Every product is tagged with concern / ingredient / routine-step so the
 * quiz, filters, cross-sell and review filtering all read one taxonomy.
 * Swap for live Shopify products by setting the Storefront env vars.
 */
export const catalog: Product[] = [
  {
    id: "ghk-cu-serum",
    handle: "ghk-cu-copper-peptide-serum",
    title: "GHK-Cu Copper Peptide Serum",
    brand: "Depris Lab",
    category: "cosmetic-peps",
    tagline: "The signature copper peptide for firmer, renewed skin.",
    description:
      "A concentrated GHK-Cu copper tripeptide serum that supports collagen, smooths the look of fine lines and strengthens the skin barrier. The active that put Depris on the map.",
    price: 42,
    currency: USD,
    tone: "bronze",
    images: [{ alt: "GHK-Cu Copper Peptide Serum bottle", tone: "bronze" }],
    variants: [
      { id: "ghk-10ml", title: "10 ml", price: 42, available: true },
      { id: "ghk-30ml", title: "30 ml", price: 95, available: true },
    ],
    concerns: ["aging", "dullness", "redness"],
    ingredients: ["copper-peptides"],
    heroIngredients: [
      { name: "Copper Tripeptide-1", inci: "Copper Tripeptide-1 (GHK-Cu)", benefit: "Supports collagen & firmness" },
      { name: "Hyaluronic Acid", inci: "Sodium Hyaluronate", benefit: "Deep, cushioning hydration" },
    ],
    routineStep: "treat",
    skinTypes: ["dry", "normal", "combination", "sensitive"],
    howToUse: "After cleansing and toning, apply 3–4 drops to clean skin before moisturizer, AM and PM.",
    clinicalClaim: "92% saw firmer-looking skin in 4 weeks*",
    rating: 4.9,
    reviewCount: 318,
    bestseller: true,
    subscribable: true,
    pairsWith: ["bellmona-clear-ampoule", "centella-calming-toner", "glass-skin-moisturizer"],
    reviews: [
      { author: "Mina K.", rating: 5, skinType: "combination", concern: "aging", title: "Noticeable bounce", body: "Four weeks in and my skin looks plumper and smoother. The copper tint feels luxe.", verified: true, date: "2026-08-12" },
      { author: "Dr. L.", rating: 5, skinType: "dry", concern: "aging", title: "Real peptide, real results", body: "Finally a GHK-Cu at a sensible strength. Barrier feels stronger.", verified: true, date: "2026-07-30" },
      { author: "Priya S.", rating: 4, skinType: "sensitive", concern: "redness", title: "Gentle but effective", body: "No irritation at all, and my redness has calmed.", verified: true, date: "2026-09-02" },
    ],
  },
  {
    id: "ahk-cu-topical",
    handle: "ahk-cu-topical-cosmetic",
    title: "AHK-Cu Topical Cosmetic",
    brand: "Depris Lab",
    category: "cosmetic-peps",
    tagline: "Copper peptide concentrate for hair, scalp and skin renewal.",
    description:
      "AHK-Cu copper peptide powder-to-serum concentrate favored for scalp and hair vitality as well as skin renewal. A pro-grade active.",
    price: 25,
    currency: USD,
    tone: "bronze",
    images: [{ alt: "AHK-Cu Topical Cosmetic vial", tone: "bronze" }],
    variants: [{ id: "ahk-1g", title: "1 g", price: 25, available: true }],
    concerns: ["aging", "dullness"],
    ingredients: ["copper-peptides"],
    heroIngredients: [{ name: "AHK Copper Peptide", inci: "Copper Tripeptide-1 blend", benefit: "Renewal & scalp vitality" }],
    routineStep: "boost",
    skinTypes: ["normal", "combination", "oily"],
    howToUse: "Reconstitute per instructions and apply to target areas. For advanced users.",
    rating: 4.8,
    reviewCount: 142,
    subscribable: true,
    pairsWith: ["exosome-scalp-ampoule"],
  },
  {
    id: "copper-peptide-duo",
    handle: "copper-peptide-duo-offer",
    title: "Copper Peptide Duo (GHK-Cu + AHK-Cu)",
    brand: "Depris Lab",
    category: "promos",
    tagline: "The complete copper peptide ritual — save 14%.",
    description: "Our two signature copper peptides together: GHK-Cu for firmness and AHK-Cu for renewal.",
    price: 37,
    compareAtPrice: 43,
    currency: USD,
    tone: "blush",
    images: [{ alt: "Copper Peptide Duo set", tone: "blush" }],
    variants: [{ id: "duo-set", title: "2-pack", price: 37, compareAtPrice: 43, available: true }],
    concerns: ["aging", "dullness"],
    ingredients: ["copper-peptides"],
    heroIngredients: [{ name: "Copper Peptides", inci: "Copper Tripeptide-1", benefit: "Firmness + renewal" }],
    routineStep: "treat",
    skinTypes: ["dry", "normal", "combination"],
    howToUse: "Use GHK-Cu AM/PM on the face; AHK-Cu on scalp or targeted areas.",
    rating: 4.9,
    reviewCount: 64,
    bestseller: true,
  },
  {
    id: "2xsome-skin-booster",
    handle: "2xsome-skin-booster",
    title: "2XSOME Skin Booster",
    brand: "2XSOME",
    category: "skin-boosters",
    tagline: "Exosome skin booster for a next-level glow.",
    description:
      "A professional-grade exosome skin booster that supercharges radiance, elasticity and post-procedure recovery.",
    price: 75,
    currency: USD,
    tone: "sage",
    images: [{ alt: "2XSOME Skin Booster box", tone: "sage" }],
    variants: [{ id: "2xsome-std", title: "1 kit", price: 75, available: true }],
    concerns: ["dullness", "aging", "redness"],
    ingredients: ["exosomes"],
    heroIngredients: [{ name: "Exosomes", inci: "Exosome complex", benefit: "Radiance & recovery" }],
    routineStep: "pro",
    skinTypes: ["normal", "dry", "combination"],
    howToUse: "For professional or advanced at-home use. Follow included protocol.",
    clinicalClaim: "Visibly brighter skin after one protocol*",
    rating: 4.9,
    reviewCount: 57,
    isNew: true,
  },
  {
    id: "art-line-plus",
    handle: "art-line-plus-solution",
    title: "ART-LINE PLUS Solution",
    brand: "ART-LINE",
    category: "skin-boosters",
    tagline: "Polynucleotide-inspired booster for resilient, glowing skin.",
    description: "A skin-boosting solution for elasticity and deep hydration, available in multiple strengths.",
    price: 24,
    compareAtPrice: 95,
    currency: USD,
    tone: "sage",
    images: [{ alt: "ART-LINE PLUS Solution", tone: "sage" }],
    variants: [
      { id: "artline-mini", title: "Starter", price: 24, available: true },
      { id: "artline-pro", title: "Pro kit", price: 95, available: true },
    ],
    concerns: ["aging", "dryness"],
    ingredients: ["exosomes", "hyaluronic-acid"],
    heroIngredients: [{ name: "Skin booster complex", inci: "Polynucleotide blend", benefit: "Elasticity & hydration" }],
    routineStep: "pro",
    skinTypes: ["dry", "normal"],
    howToUse: "Advanced use. Follow the included protocol.",
    rating: 4.7,
    reviewCount: 39,
  },
  {
    id: "bellmona-clear-ampoule",
    handle: "bellmona-clear-ampoule",
    title: "Bellmona Clear Ampoule",
    brand: "Bellmona",
    category: "serums",
    tagline: "Lightweight clarifying ampoule for fresh, balanced skin.",
    description: "A daily ampoule that clarifies and hydrates, leaving skin fresh, smooth and balanced.",
    price: 13,
    currency: USD,
    tone: "blush",
    images: [{ alt: "Bellmona Clear Ampoule", tone: "blush" }],
    variants: [{ id: "bell-clear-30", title: "30 ml", price: 13, available: true }],
    concerns: ["acne", "pores", "dullness"],
    ingredients: ["niacinamide", "centella"],
    heroIngredients: [
      { name: "Niacinamide", inci: "Niacinamide", benefit: "Brightens & refines pores" },
      { name: "Centella", inci: "Centella Asiatica Extract", benefit: "Calms & soothes" },
    ],
    routineStep: "treat",
    skinTypes: ["oily", "combination", "normal"],
    howToUse: "Apply after toner, morning and night.",
    rating: 4.8,
    reviewCount: 211,
    bestseller: true,
    subscribable: true,
    pairsWith: ["ghk-cu-copper-peptide-serum", "centella-calming-toner"],
  },
  {
    id: "bellmona-cc-sunscreen",
    handle: "bellmona-cc-cream-sunscreen",
    title: "Bellmona CC Cream Sunscreen",
    brand: "Bellmona",
    category: "sunscreen-bb-cc",
    tagline: "Luminous tinted SPF for everyday protection.",
    description: "A lightweight CC cream with broad-spectrum SPF that evens tone and gives a natural, glowing finish.",
    price: 28,
    currency: USD,
    tone: "bronze",
    images: [{ alt: "Bellmona CC Cream Sunscreen", tone: "bronze" }],
    variants: [
      { id: "cc-light", title: "Light", price: 28, available: true },
      { id: "cc-medium", title: "Medium", price: 28, available: true },
    ],
    concerns: ["pigmentation", "dullness"],
    ingredients: ["spf", "niacinamide"],
    heroIngredients: [{ name: "Broad-spectrum SPF", inci: "Zinc Oxide / Titanium Dioxide", benefit: "Daily UV protection" }],
    routineStep: "spf",
    skinTypes: ["normal", "dry", "combination", "oily"],
    howToUse: "Apply as the last step of your morning routine. Reapply through the day.",
    rating: 4.7,
    reviewCount: 168,
    bestseller: true,
  },
  {
    id: "bellmona-tox-cream",
    handle: "bellmona-holding-time-tox-cream",
    title: "Bellmona Holding Time TOX Cream",
    brand: "Bellmona",
    category: "face-cream-peels",
    tagline: "Firming peptide cream for a lifted, smooth look.",
    description: "A rich peptide cream that visibly firms and smooths while deeply moisturizing.",
    price: 36,
    currency: USD,
    tone: "blush",
    images: [{ alt: "Bellmona Holding Time TOX Cream jar", tone: "blush" }],
    variants: [{ id: "tox-50", title: "50 ml", price: 36, available: true }],
    concerns: ["aging", "dryness"],
    ingredients: ["copper-peptides", "hyaluronic-acid"],
    heroIngredients: [{ name: "Peptide complex", inci: "Palmitoyl Tripeptide blend", benefit: "Firms & smooths" }],
    routineStep: "moisturize",
    skinTypes: ["dry", "normal"],
    howToUse: "Apply as the final nourishing step, AM and PM.",
    rating: 4.8,
    reviewCount: 96,
    subscribable: true,
    pairsWith: ["ghk-cu-copper-peptide-serum"],
  },
  {
    id: "centella-calming-toner",
    handle: "centella-calming-toner",
    title: "Centella Calming Toner",
    brand: "Bellmona",
    category: "cleansers-toners",
    tagline: "Soothing cica toner that preps and calms.",
    description: "A hydrating toner with Centella Asiatica to calm redness and prep skin for the rest of your routine.",
    price: 18,
    currency: USD,
    tone: "sage",
    images: [{ alt: "Centella Calming Toner bottle", tone: "sage" }],
    variants: [{ id: "cica-toner-200", title: "200 ml", price: 18, available: true }],
    concerns: ["redness", "acne"],
    ingredients: ["centella", "hyaluronic-acid"],
    heroIngredients: [{ name: "Centella Asiatica", inci: "Centella Asiatica Extract", benefit: "Calms & strengthens barrier" }],
    routineStep: "tone",
    skinTypes: ["sensitive", "combination", "oily", "normal"],
    howToUse: "Sweep over clean skin with a cotton pad or press in with palms.",
    rating: 4.7,
    reviewCount: 134,
  },
  {
    id: "gentle-gel-cleanser",
    handle: "gentle-gel-cleanser",
    title: "Low-pH Gentle Gel Cleanser",
    brand: "Bellmona",
    category: "cleansers-toners",
    tagline: "A barrier-friendly daily cleanser.",
    description: "A low-pH gel cleanser that removes impurities without stripping, leaving skin soft and balanced.",
    price: 16,
    currency: USD,
    tone: "sand",
    images: [{ alt: "Low-pH Gentle Gel Cleanser", tone: "sand" }],
    variants: [{ id: "cleanser-150", title: "150 ml", price: 16, available: true }],
    concerns: ["acne", "redness", "pores"],
    ingredients: ["centella"],
    heroIngredients: [{ name: "Low-pH formula", inci: "Coco-Betaine blend", benefit: "Cleanses without stripping" }],
    routineStep: "cleanse",
    skinTypes: ["oily", "combination", "normal", "sensitive"],
    howToUse: "Massage onto damp skin, rinse with lukewarm water. AM and PM.",
    rating: 4.6,
    reviewCount: 203,
    bestseller: true,
  },
  {
    id: "vitamin-c-glow-serum",
    handle: "vitamin-c-glow-serum",
    title: "Vitamin C Glow Serum",
    brand: "Depris Lab",
    category: "serums",
    tagline: "15% vitamin C for luminous, even-toned skin.",
    description: "A stable vitamin C serum that brightens, fades dark spots and defends against daily stressors.",
    price: 29,
    currency: USD,
    tone: "bronze",
    images: [{ alt: "Vitamin C Glow Serum", tone: "bronze" }],
    variants: [{ id: "vitc-30", title: "30 ml", price: 29, available: true }],
    concerns: ["pigmentation", "dullness"],
    ingredients: ["vitamin-c", "niacinamide"],
    heroIngredients: [{ name: "Vitamin C", inci: "Ascorbic Acid (15%)", benefit: "Brightens & evens tone" }],
    routineStep: "treat",
    skinTypes: ["normal", "combination", "oily", "dry"],
    howToUse: "Apply 3–4 drops in the morning before SPF.",
    clinicalClaim: "88% saw brighter skin in 2 weeks*",
    rating: 4.7,
    reviewCount: 177,
    subscribable: true,
    pairsWith: ["bellmona-cc-cream-sunscreen"],
  },
  {
    id: "retinol-renewal-night",
    handle: "retinol-renewal-night-serum",
    title: "Retinol Renewal Night Serum",
    brand: "Depris Lab",
    category: "serums",
    tagline: "Encapsulated retinol for smoother, refined skin.",
    description: "A gentle encapsulated retinol that smooths texture and softens fine lines while you sleep.",
    price: 34,
    currency: USD,
    tone: "ink",
    images: [{ alt: "Retinol Renewal Night Serum", tone: "ink" }],
    variants: [{ id: "retinol-30", title: "30 ml", price: 34, available: true }],
    concerns: ["aging", "pores", "dullness"],
    ingredients: ["retinol", "niacinamide"],
    heroIngredients: [{ name: "Encapsulated Retinol", inci: "Retinol 0.3%", benefit: "Smooths & refines" }],
    routineStep: "treat",
    skinTypes: ["normal", "combination", "oily"],
    howToUse: "Apply at night 2–3x per week to start, building up as tolerated. Always wear SPF.",
    rating: 4.6,
    reviewCount: 118,
    subscribable: true,
  },
  {
    id: "snail-repair-essence",
    handle: "snail-repair-essence",
    title: "Snail Repair Essence",
    brand: "Bellmona",
    category: "serums",
    tagline: "Snail mucin essence for dewy, bouncy skin.",
    description: "A silky essence rich in snail secretion filtrate that repairs, hydrates and gives instant dewiness.",
    price: 22,
    currency: USD,
    tone: "blush",
    images: [{ alt: "Snail Repair Essence", tone: "blush" }],
    variants: [{ id: "snail-100", title: "100 ml", price: 22, available: true }],
    concerns: ["dryness", "redness", "pigmentation"],
    ingredients: ["snail-mucin", "hyaluronic-acid"],
    heroIngredients: [{ name: "Snail Secretion Filtrate", inci: "Snail Secretion Filtrate", benefit: "Repairs & hydrates" }],
    routineStep: "boost",
    skinTypes: ["dry", "normal", "sensitive", "combination"],
    howToUse: "Pat a few drops onto skin after toner, before serum.",
    rating: 4.8,
    reviewCount: 256,
    bestseller: true,
  },
  {
    id: "hyaluronic-dew-mask",
    handle: "hyaluronic-dew-sheet-mask",
    title: "Hyaluronic Dew Sheet Mask",
    brand: "Bellmona",
    category: "sheet-masks",
    tagline: "Ten-minute hydration ritual.",
    description: "A drenching sheet mask that floods skin with hyaluronic acid for an instant plump glow.",
    price: 4,
    currency: USD,
    tone: "blush",
    images: [{ alt: "Hyaluronic Dew Sheet Mask", tone: "blush" }],
    variants: [
      { id: "mask-1", title: "Single", price: 4, available: true },
      { id: "mask-5", title: "5-pack", price: 18, available: true },
    ],
    concerns: ["dryness", "dullness"],
    ingredients: ["hyaluronic-acid"],
    heroIngredients: [{ name: "Hyaluronic Acid", inci: "Sodium Hyaluronate", benefit: "Instant hydration" }],
    routineStep: "boost",
    skinTypes: ["dry", "normal", "sensitive", "combination", "oily"],
    howToUse: "Apply to clean skin for 10–15 minutes, then pat in the remaining essence.",
    rating: 4.7,
    reviewCount: 312,
  },
  {
    id: "niacinamide-pore-serum",
    handle: "niacinamide-pore-refining-serum",
    title: "Niacinamide Pore-Refining Serum",
    brand: "Depris Lab",
    category: "serums",
    tagline: "10% niacinamide to refine pores and balance oil.",
    description: "A lightweight serum that visibly minimizes pores, controls shine and strengthens the barrier.",
    price: 21,
    currency: USD,
    tone: "sage",
    images: [{ alt: "Niacinamide Pore-Refining Serum", tone: "sage" }],
    variants: [{ id: "niac-30", title: "30 ml", price: 21, available: true }],
    concerns: ["pores", "acne", "pigmentation"],
    ingredients: ["niacinamide"],
    heroIngredients: [{ name: "Niacinamide", inci: "Niacinamide 10%", benefit: "Refines pores, balances oil" }],
    routineStep: "treat",
    skinTypes: ["oily", "combination", "normal"],
    howToUse: "Apply morning and night after toner.",
    rating: 4.6,
    reviewCount: 149,
  },
  {
    id: "aha-bha-peel",
    handle: "aha-bha-resurfacing-peel",
    title: "AHA/BHA Resurfacing Peel",
    brand: "Depris Lab",
    category: "face-cream-peels",
    tagline: "Weekly exfoliating peel for smooth, clear skin.",
    description: "A gentle leave-on peel with AHA and BHA that resurfaces, unclogs pores and renews radiance.",
    price: 26,
    currency: USD,
    tone: "sand",
    images: [{ alt: "AHA/BHA Resurfacing Peel", tone: "sand" }],
    variants: [{ id: "peel-100", title: "100 ml", price: 26, available: true }],
    concerns: ["acne", "pores", "dullness", "pigmentation"],
    ingredients: ["aha-bha"],
    heroIngredients: [{ name: "AHA + BHA", inci: "Glycolic Acid / Salicylic Acid", benefit: "Resurfaces & unclogs" }],
    routineStep: "treat",
    skinTypes: ["oily", "combination", "normal"],
    howToUse: "Apply 1–2x weekly at night after cleansing. Follow with moisturizer and SPF the next day.",
    rating: 4.6,
    reviewCount: 88,
  },
  {
    id: "glass-skin-moisturizer",
    handle: "glass-skin-moisturizer",
    title: "Glass-Skin Gel Moisturizer",
    brand: "Bellmona",
    category: "face-cream-peels",
    tagline: "Weightless gel-cream for a dewy finish.",
    description: "A bouncy gel-cream that locks in moisture for that coveted glass-skin glow, without any heaviness.",
    price: 24,
    currency: USD,
    tone: "blush",
    images: [{ alt: "Glass-Skin Gel Moisturizer jar", tone: "blush" }],
    variants: [{ id: "glass-50", title: "50 ml", price: 24, available: true }],
    concerns: ["dryness", "dullness", "redness"],
    ingredients: ["hyaluronic-acid", "centella"],
    heroIngredients: [{ name: "Hyaluronic Acid", inci: "Sodium Hyaluronate", benefit: "Lightweight hydration" }],
    routineStep: "moisturize",
    skinTypes: ["combination", "oily", "normal", "sensitive"],
    howToUse: "Smooth over skin as the final step, AM and PM.",
    rating: 4.8,
    reviewCount: 221,
    bestseller: true,
    subscribable: true,
  },
  {
    id: "exosome-scalp-ampoule",
    handle: "exosome-scalp-ampoule",
    title: "Exosome Scalp & Hair Ampoule",
    brand: "2XSOME",
    category: "hair-exosomes",
    tagline: "Exosome treatment for fuller, healthier-looking hair.",
    description: "A leave-in scalp ampoule powered by exosomes to support density, scalp health and shine.",
    price: 48,
    currency: USD,
    tone: "sage",
    images: [{ alt: "Exosome Scalp & Hair Ampoule", tone: "sage" }],
    variants: [{ id: "exo-scalp-50", title: "50 ml", price: 48, available: true }],
    concerns: ["aging"],
    ingredients: ["exosomes", "copper-peptides"],
    heroIngredients: [{ name: "Exosomes", inci: "Exosome complex", benefit: "Scalp vitality & density" }],
    routineStep: "pro",
    skinTypes: ["normal"],
    howToUse: "Massage into a clean, dry scalp daily. Do not rinse.",
    rating: 4.7,
    reviewCount: 73,
    isNew: true,
    subscribable: true,
  },
  {
    id: "microneedling-pen",
    handle: "home-microneedling-pen",
    title: "At-Home Microneedling Pen",
    brand: "Depris Devices",
    category: "microneedling",
    tagline: "Pro-style resurfacing, at home.",
    description: "A precision microneedling device with adjustable depth to boost absorption and renew skin texture.",
    price: 59,
    currency: USD,
    tone: "ink",
    images: [{ alt: "At-Home Microneedling Pen", tone: "ink" }],
    variants: [{ id: "pen-std", title: "Device + 5 tips", price: 59, available: true }],
    concerns: ["aging", "pigmentation", "pores"],
    ingredients: [],
    heroIngredients: [{ name: "Adjustable depth", inci: "0.25–1.5 mm", benefit: "Boosts absorption & renewal" }],
    routineStep: "pro",
    skinTypes: ["normal", "combination", "oily"],
    howToUse: "Use on clean skin per the included guide. Pair with a skin booster for best results.",
    rating: 4.5,
    reviewCount: 61,
    pairsWith: ["2xsome-skin-booster", "ghk-cu-copper-peptide-serum"],
  },
  {
    id: "glow-vitamins",
    handle: "inner-glow-skin-vitamins",
    title: "Inner Glow Skin Vitamins",
    brand: "Depris Wellness",
    category: "vitamins-wellness",
    tagline: "Beauty from within — skin, hair & nails.",
    description: "A daily supplement with antioxidants, biotin and marine collagen to support glow from the inside out.",
    price: 32,
    currency: USD,
    tone: "bronze",
    images: [{ alt: "Inner Glow Skin Vitamins bottle", tone: "bronze" }],
    variants: [{ id: "vit-30", title: "30-day", price: 32, available: true }],
    concerns: ["dullness", "aging"],
    ingredients: [],
    heroIngredients: [{ name: "Marine Collagen", inci: "Hydrolyzed Collagen", benefit: "Supports skin elasticity" }],
    routineStep: "boost",
    skinTypes: ["normal", "dry", "combination", "oily", "sensitive"],
    howToUse: "Take two capsules daily with food.",
    rating: 4.5,
    reviewCount: 94,
    subscribable: true,
  },
];
